scan:
  input_dir: "C:/Users/Daniel/Downloads/Data_Quality/data"
  file_patterns:
    - "*.csv"
    - "*.xlsx"
    - "*.xls"
    - "*.parquet"
  csv_sep: ","
  csv_encoding: "utf-8"

duckdb:
  path: "./dq_lab.duckdb"
  schema: "stg"

rules:
  path: "config/12_dq_rules.yml"

output:
  dir: "./output"

postgres:
  enabled: false
  host: "${POSTGRES_HOST}"
  port: 5432
  db: "${POSTGRES_DB}"
  user: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"
  include_schemas:
    - public
  include_tables:
    - "public.clientes_teste"
  limit: 50000